build:
    go build -o myapp

run:
    go run main.go

test:
    go test ./...

lint:
    @hash golangci-lint > /dev/null 2>&1; if [ $$? -ne 0 ]; then \
        export BINARY="golangci-lint"; \
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $$(go env GOPATH)/bin v1.31.0; \
    fi
    golangci-lint run --timeout 5m

clean:
    go clean
    rm -f myapp

.PHONY: build run test lint clean
