# .github/workflows/ci.yml

name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20 # Replace with your desired Go version

      - name: Install linters
        run: |
          go install golang.org/x/lint/golint
          go install golang.org/x/tools/cmd/goimports

      - name: Lint with GoLint
        run: golint ./...

      - name: Lint with Go vet
        run: go vet ./...
